// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgtwffsfipirwyymewph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndHdmZnNmaXBpcnd5eW1ld3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNDc3NjgsImV4cCI6MjA3NjcyMzc2OH0.SAIiPAa3F3zCty2YalsB3o2-riuDc9xMukWXdytTTTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});